---
- hosts: all
  tasks:
    - name: Set OS distribution dependent variables
      include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"
      when: ansible_facts['os_family'] == "Debian"

# Install OMERO.server and OMERO.web with a public user on localhost
- hosts: all
  roles:

    - role: ome.postgresql
      postgresql_install_server: true
      postgresql_databases:
        - name: omero
      postgresql_users:
        - user: omero
          password: omero
          databases: [omero]
      postgresql_version: "11"

    - role: ome.omero_server
      omero_server_release: latest

    - role: ome.omero_web
      omero_web_config_set:
        omero.web.public.enabled: true
        omero.web.public.server_id: 1
        omero.web.public.user: public
        omero.web.public.password: "{{ omero_web_public_password }}"
        omero.web.public.url_filter: "^/(webadmin/myphoto/|webclient/\
          (?!(action|logout|annotate_(file|tags|comment|rating|map)|\
          script_ui|ome_tiff|figure_script))|\
          webgateway/(?!(archived_files|download_as)))"


    # This role only works on OMERO 5.3+
    - role: ome.omero_user
      omero_user_system: omero-server
      omero_user_admin_user: root
      omero_user_admin_pass: omero
      omero_group_create:
        - name: demo
          type: read-only
      omero_user_create:
        - login: public
          firstname: public
          lastname: user
          password: "{{ omero_web_public_password }}"
          groups: "--group-name demo"

  vars:
    omero_web_public_password: public
    ## PRODUCTION VARIABLES: For a production system,
    ## remove "_DISABLED" from the following property
    ## in order to scale up for more users. Disabling
    ## permits testing on smaller VMs.
    omero_server_config_set_DISABLED:
      omero.db.poolsize: 50
      omero.jvmcfg.percent.blitz: 50
      omero.jvmcfg.percent.indexer: 20
      omero.jvmcfg.percent.pixeldata: 20
