---

- src: ome.postgresql
  version: 4.0.0

- src: ome.omero_server
  version: 3.0.0

- src: ome.omero_web
  version: 3.0.1

- name: ome.omero_user
  src: "https://github.com/ome/ansible-role-omero-user/archive/\
     ede99d4e3a98453216149dd3e5d631e976fb4540.tar.gz"
